### PR TITLE
🔄 synced file(s) with SumoLogic/sumologic-otel-collector-packaging

### PR DESCRIPTION
**Pull request by sumologic-sanyaku-apps**
synced local file(s) with [SumoLogic/sumologic-otel-collector-packaging](https://github.com/SumoLogic/sumologic-otel-collector-packaging).

<details>
<summary>Changed files</summary>
<ul>
<li>created local  <code>assets/sumologic.yaml</code>  from remote  <code>assets/sumologic.yaml</code></li><li>created local  <code>assets/sumologic-windows.yaml</code>  from remote  <code>assets/sumologic-windows.yaml</code></li>
</ul>
</details>

---

This PR was created automatically by the [repo-file-sync-action](https://github.com/BetaHuhn/repo-file-sync-action) workflow run [#11847439887](https://github.com/SumoLogic/sumologic-otel-collector-packaging/actions/runs/11847439887)

### CODE REVIEW

**Review by sumo-drosiek — CHANGES_REQUESTED** [review]
Do we really want to sync to this repository? 😕

**Comment by echlebek** [comment]
@amdprophet can you comment?

**Comment by amdprophet** [comment]
> @amdprophet can you comment?

Maybe not. CI pulls the install scripts from the packaging repo when it attaches artifacts to the release. I think we should remove this sync job and close this PR.

**Comment by amdprophet** [comment]
I removed the sync job from the packaging repo: https://github.com/SumoLogic/sumologic-otel-collector-packaging/pull/128.

**Pull request closed without merging**
