### PR TITLE
Update docs and examples to use the most recent otelcol version

### PR DESCRIPTION
**Pull request by perk-sumo**

### CODE REVIEW

**Review by pmalek-sumo — APPROVED** [review]
NOTE: that 0.0.53-beta.0 is not yet ready :)

**Comment by perk-sumo** [comment]
Good call! Changed that into `0.0.52-beta.0`.

**Comment by swiatekm-sumo** [comment]
Should we automate this in some way? Or maybe just replace all of these concrete values with a placeholder like `<version>`?

**Comment by pmalek-sumo** [comment]
> Should we automate this in some way? Or maybe just replace all of these concrete values with a placeholder like `<version>`?

No point I think. When this gets out of beta we'll use releases instead of prereleases and then https://github.com/SumoLogic/sumologic-otel-collector/releases/latest will work.

**Pull request merged**
