### PR TITLE
feat(sumologicextension): deprecate install_token in favor of installation_token

### PR DESCRIPTION
**Pull request by sumo-drosiek**
Signed-off-by: Dominik Rosiek <drosiek@sumologic.com>

### CODE REVIEW

**Comment by astencel-sumo** [comment]
Should we use a feature gate for this breaking change? This is recommended by upstream here: https://github.com/open-telemetry/opentelemetry-collector/blob/v0.71.0/CONTRIBUTING.md#breaking-changes.

> When deprecating a feature affecting end-users, consider first deprecating the feature in one version, then hiding it behind a [feature flag](https://github.com/open-telemetry/opentelemetry-collector/blob/6b5a3d08a96bfb41a5e121b34f592a1d5c6e0435/service/featuregate/) in a subsequent version, and eventually removing it after yet another version.

**Comment by sumo-drosiek** [comment]
> Should we use a feature gate for this breaking change? This is recommended by upstream here: https://github.com/open-telemetry/opentelemetry-collector/blob/v0.71.0/CONTRIBUTING.md#breaking-changes.
> 
> > When deprecating a feature affecting end-users, consider first deprecating the feature in one version, then hiding it behind a [feature flag](https://github.com/open-telemetry/opentelemetry-collector/blob/6b5a3d08a96bfb41a5e121b34f592a1d5c6e0435/service/featuregate/) in a subsequent version, and eventually removing it after yet another version.

Technically this change itself is not a breaking change. Removing `install_token` will be a breaking change, and we can do it with `feature_flag`

I don't want to do a rename as a breaking change, because there will be problem with synchronising this change with UI, install script and documentation changes.

**Comment by astencel-sumo** [comment]
We decided to not use a feature flag. Changing the config option `install_token` to `installation_token` is probably even easier than adding a feature flag CLI option to the binary invocation, so it doesn't seem to be worth it.

**Review by astencel-sumo — COMMENTED** [review]
So you're adding a new configuration option `installation_token` but not updating the docs? :thinking:

**Review by astencel-sumo — APPROVED** [review]

**Pull request merged**
