### PR TITLE
feat(sumologicextension): deprecate in favor of OpenTelemetry Contrib extension

### PR DESCRIPTION
**Pull request by sumo-drosiek**
Deprecate Sumo Logic Extension in favor of upstream ones

### CODE REVIEW

**Comment by swiatekm-sumo** [comment]
Should we also change the extension in sumo exporter's go.mod?

**Comment by sumo-drosiek** [comment]
Converting to draft as waiting for new OpenTelemetry Collector Release

**Comment by rnishtala-sumo** [comment]
@sumo-drosiek Are there any breaking changes with this? Maybe we could capture differences (if any) between the upstream extension and the local one, just to be sure they haven't diverged feature-wise.

**Comment by sumo-drosiek** [comment]
@rnishtala-sumo There shouldn't be any. I don't see any traffic in extension from 3 month. It should be basically the same code

**Pull request merged**
