### PR TITLE
fix(cascading_filter): fix leak on traces where decision was made

### PR DESCRIPTION
**Pull request by pmm-sumo**
This fixes the case with increased memory consumption when spans for traces where decision was already made are observed

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
I made some calculations and test should take about 20s, is it possible to reduce it somehow?

**Comment by pmm-sumo** [comment]
> I made some calculations and test should take about 20s, is it possible to reduce it somehow?

So that's the bummer with it, the shortest interval for compaction to kick is 1s. With margin, this gets bigger. I'm thinking about either disabling the test or changing the internal API to accept shorter intervals

**Comment by sumo-drosiek** [comment]
We can add some comment to the test and if it will be too annoying we can fix it then. Of course you can fix it now as well :)

**Comment by pmm-sumo** [comment]
@sumo-drosiek the fix won't be that simple so I skipped the test for now. I am keen to rework the underlying architecture of the cascading filter and then we could fix that as well

**Pull request merged**
