### PR TITLE
feat(sumologicextension): use different key for encryption and filename

### PR DESCRIPTION
**Pull request by pmalek-sumo**

### CODE REVIEW

**Review by sumo-drosiek — APPROVED** [review]
> What is difference between key and passphrase in hashing functions?

Nothing 😅 I was also hesitant on the naming. I can make them both `key`s if you feel that would be better

**Comment by pmalek-sumo** [comment]
> What is difference between key and passphrase in hashing functions?

Nothing 😅 I was also hesitant on the naming. I can make them both `key`s if you feel that would be better

**Comment by sumo-drosiek** [comment]
I would make it consistent :)
`key` is fine

**Comment by pmalek-sumo** [comment]
> I would make it consistent :) `key` is fine

done

**Review by sumo-drosiek — APPROVED** [review]

**Pull request merged**
