### PR TITLE
fix(k8s_tagger) Removing k8s tagger warnings, as these have been causing false alarms and cost concerns

### PR DESCRIPTION
**Pull request by rnishtala-sumo**
Removing k8s tagger warnings, as these have been causing false alarms and cost concerns

### CODE REVIEW

**Comment by echlebek** [comment]
@rnishtala-sumo is it worth making these debug level instead of removing them? Do they carry any debugging value?

**Comment by echlebek** [comment]
Seems like it would only be useful to say how long the cache has been out of sync for, or maybe only log if it's been out of sync for a much longer period than expected. That said, this is still an improvement. :+1:

**Review by echlebek — APPROVED** [review]

**Comment by chan-tim-sumo** [comment]
Should this go down to Info level from warn level instead of going to debug? because i'm thinking this still runs in production right? and if i remember correctly, debug is disabled in production 🤔

**Comment by rnishtala-sumo** [comment]
@chan-tim-sumo The goal is to not see them in prod by default. But have the option of enabling them. Debug is used for such use cases.

**Review by chan-tim-sumo — APPROVED** [review]

**Pull request merged**
