### PR TITLE
docs(configuration): add example for keeping prometheus format with OTLP

### PR DESCRIPTION
**Pull request by sumo-drosiek**
This solution is not perfect but there is not so many alternatives

### CODE REVIEW

**Review by pmalek-sumo — COMMENTED** [review]
Have you tested this with jmx metrics which have dots in field names (which are translated in telegrafreceiver to OT's data point labels)?

Wouldn't this only update the metrics names and not the data point labels?

**Comment by sumo-drosiek** [comment]
@pmalek-sumo Yes, and then we have `field` dimension  (with dot of course)

**Comment by pmalek-sumo** [comment]
> @pmalek-sumo Yes, and then we have `field` dimension (with dot of course)

Shouldn't we document that separately then?

**Comment by sumo-drosiek** [comment]
Not sure as app dashboards do not rely on them and also I don't see possibility to change field value using regexp

**Comment by pmalek-sumo** [comment]
> Not sure as app dashboards do not rely on them and also I don't see possibility to change field value using regexp

Now I'm confused 😕  Wasn't the problem about fields like e.g. `Utilization.min`? Isn't that what we're trying to cover here?

**Comment by sumo-drosiek** [comment]
the problem is with field indeed, but in case this field has been added to metric name so we had:

`metric_name_Utilization.max`, but we would like to have `metric_name_Utilization_max`

so, field in telegraf but metric name in OTC

**Comment by pmalek-sumo** [comment]
> the problem is with field indeed, but in case this field has been added to metric name so we had:
> 
> `metric_name_Utilization.max`, but we would like to have `metric_name_Utilization_max`
> 
> so, field in telegraf but metric name in OTC

What if someone uses `separate_field: true` in [telegrafreceiver](https://github.com/SumoLogic/sumologic-otel-collector/tree/main/pkg/receiver/telegrafreceiver)? Then the field becomes a data point label

**Comment by sumo-drosiek** [comment]
> What if someone uses separate_field: true in [telegrafreceiver](https://github.com/SumoLogic/sumologic-otel-collector/tree/main/pkg/receiver/telegrafreceiver)? Then the field becomes a data point label

yes, but we don't use scenario with `separate_field: true` for application dashboards, also dot is fine as label value in prometheus format

**Review by pmalek-sumo — APPROVED** [review]

**Pull request merged**
