### PR TITLE
feat(exporter/syslog): deprecate syslog exporter in favor of upstream version of syslog exporter

### PR DESCRIPTION
**Pull request by kkujawa-sumo**
Related to #1341

### CODE REVIEW

**Review by aboguszewski-sumo — COMMENTED** [review]
Please also change it in the code:

https://github.com/SumoLogic/sumologic-otel-collector/blob/6ad4db6e4ad9d53d91bc3c58a4dea373003f9766/pkg/exporter/syslogexporter/factory.go#L29

**Review by swiatekm-sumo — APPROVED** [review]

**Comment by aboguszewski-sumo** [comment]
Also a comment: maybe in the future we should try to name the components we're pushing into upstream differently than there. This way we won't have such breaking changes.

**Review by aboguszewski-sumo — APPROVED** [review]

**Comment by swiatekm-sumo** [comment]
> Also a comment: maybe in the future we should try to name the components we're pushing into upstream differently than there. This way we won't have such breaking changes.

Would that have helped us avoid this deprecation?

**Comment by kkujawa-sumo** [comment]
I think that @aboguszewski-sumo meant #1341

**Review by astencel-sumo — CHANGES_REQUESTED** [review]
How can we suggest using contrib syslog exporter if we don't include it in our distro?

**Comment by aboguszewski-sumo** [comment]
@astencel-sumo we will once https://github.com/SumoLogic/sumologic-otel-collector/pull/1341 is merged. But good point.

**Comment by kkujawa-sumo** [comment]
>How can we suggest using contrib syslog exporter if we don't include it in our distro?

#1341 must be merged first.

**Review by astencel-sumo — APPROVED** [review]
So the plan is to replace the Sumo Logic `syslog` exporter with upstream Contrib `syslog` exporter in the next release, `v0.90.0-sumo-0`. This is a breaking change, but only a minor configuration change is needed to upgrade, as described in #1341.

**Pull request merged**
