### PR TITLE
Configuration management release assets

### PR DESCRIPTION
**Pull request by portertech**
This allows users to download the Chef cookbook, Puppet module, and Ansible playbook with a one-liner (using the Github release "latest/download" redirect). For example:

```
curl -LO https://github.com/SumoLogic/sumologic-otel-collector/releases/latest/download/install.sh
```

For the Chef cookbook, it will look like:

```
curl -Ls https://github.com/SumoLogic/sumologic-otel-collector/releases/latest/download/chef-cookbook.tar.gz | tar -xvf
```

### CODE REVIEW

**Comment by portertech** [comment]
Gotta do Puppet and Ansible next. Not yet ready for review.

**Review by amdprophet — APPROVED** [review]

**Comment by portertech** [comment]
@amdprophet I updated the PR to also cover Puppet and Ansible. I used a single job for some efficiency.

**Review by swiatekm-sumo — APPROVED** [review]
LGTM, but I hope you've actually tested this on a fork.

**Comment by swiatekm-sumo** [comment]
I'm also wondering if we want to leave these in this repo in the long term.

**Comment by portertech** [comment]
@swiatekm-sumo proof 😆 

Screenshot 2023-04-28 at 8 45 42 PM

**Comment by portertech** [comment]
@swiatekm-sumo we don't want to leave these here in the long term, but I also don't want to put more energy into them at this time (and the related docs/links/etc) unless we find strong demand.

@amdprophet @swiatekm-sumo we can discuss the native packaging transition plan next week. We need this before we make further investments in configuration management tooling.

**Pull request merged**
