### PR TITLE
feat(sumologicextension): allow using multiple sumologicextensions

### PR DESCRIPTION
**Pull request by pmalek-sumo**

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
What if authenticator will be set to non-existing  extenstion?

**Comment by sumo-drosiek** [comment]
AFAIU: 
```
	} else {
		return fmt.Errorf("no auth extension and no endpoint specified")
}
```

this error can be misleading

**Comment by pmalek-sumo** [comment]
> What if authenticator will be set to non-existing extenstion?

Good catch! I've change the logic to account for that, please recheck

**Comment by sumo-drosiek** [comment]
I found an issue which is related to extensions, we can make another PR for that

---

```
exporters:
  sumologic:
    auth: null
    endpoint: "test_endpoint"
    log_format: json
extensions:
  health_check: {}
receivers:
  fluentforward:
    endpoint: 0.0.0.0:24321
service:
  extensions:
  - health_check
  pipelines:
    logs:
      exporters:
      - sumologic
      processors: []
      receivers:
      - fluentforward

```

```
2021-07-15T09:11:43.168+0200    info    builder/exporters_builder.go:92 Exporter is starting... {"kind": "exporter", "name": "sumologic"}
Error: cannot setup pipelines: cannot start builtExporters: failed to create HTTP Client: failed to resolve authenticator "sumologic": authenticator not found
2021/07/15 09:11:43 application run finished with error: cannot setup pipelines: cannot start builtExporters: failed to create HTTP Client: failed to resolve authenticator "sumologic": authenticator not found
```

https://github.com/SumoLogic/sumologic-otel-collector/blob/dd0a71764e877c0b718aa51090e2f0783479d279/pkg/exporter/sumologicexporter/exporter.go#L474-L477

**Comment by sumo-drosiek** [comment]
https://github.com/SumoLogic/sumologic-otel-collector/pull/106

**Review by sumo-drosiek — APPROVED** [review]

**Pull request merged**
