### PR TITLE
fix: change attribute translation

### PR DESCRIPTION
**Pull request by kkujawa-sumo**
change Namespace to namespace and Deployment to deployment

Note: metric coming from Fluentd have `namespace` and `deployment` metadata

### CODE REVIEW

**Review by pmalek-sumo — APPROVED** [review]
There are no tests for that 🙀 ?

**Comment by kkujawa-sumo** [comment]
> There are no tests for that 🙀 ?

There are tests :) I added correction also to them.

**Review by sumo-drosiek — APPROVED** [review]
:clap:

**Review by pmalek-sumo — COMMENTED** [review]
👍

**Pull request merged**
