### PR TITLE
Bump OTC to v0.38.0

### PR DESCRIPTION
**Pull request by pmm-sumo**
Updates OTC to v0.38.0

### CODE REVIEW

**Review by pmalek-sumo — APPROVED** [review]
Thanks @pmm-sumo 🚀

**Review by swiatekm-sumo — APPROVED** [review]
Does this happen frequently enough that it'd make sense to have a script to bump the version everywhere it needs to be bumped? Looks kind of annoying and error-prone.

**Comment by pmalek-sumo** [comment]
> Does this happen frequently enough that it'd make sense to have a script to bump the version everywhere it needs to be bumped? Looks kind of annoying and error-prone.

Bumping the version itself is fairly easy in pretty much every IDE (or by sed if someone's brave enough). The problematic part is that core API changes sometimes hence we need changes like done by @pmm-sumo in this PR and it's hard (impossible?) to automate this.

The only thing you could "automate" is to use `gofmt` replace but you have to write the rules for that manually anyway, e.g.

```
gofmt -r 'config.NewID(a) -> config.NewComponentID(a)' -w $(rg -l config.NewID)
```

**Comment by pmm-sumo** [comment]
Should we worry about this?
```
golangci-lint run --skip-files '(components|main|main_others|main_windows).go' .
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
```

I restarted the job

**Comment by pmalek-sumo** [comment]
> Should we worry about this?
> 
> ```
> golangci-lint run --skip-files '(components|main|main_others|main_windows).go' .
> level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
> ```
> 
> I restarted the job

I'm looking into this:

* https://github.com/SumoLogic/sumologic-otel-collector/pull/340

this should help to some extent.

**Comment by pmalek-sumo** [comment]
@pmm-sumo You can rebase/merge in the changes from `main` to start filling the cache the and builds should be faster from now on + the timeout has been extended to 10m to prevent these failures before it (cache) fills up.

**Comment by pmm-sumo** [comment]
> @pmm-sumo You can rebase/merge in the changes from `main` to start filling the cache the and builds should be faster from now on + the timeout has been extended to 10m to prevent these failures before it (cache) fills up.

I will do that! Also incorporate the branch updates

**Pull request merged**
