### PR TITLE
chore: remove routing_attributes_to_drop

### PR DESCRIPTION
**Pull request by echlebek**
The upstream issue that necessitated this configuration was closed in 2022, and special treatment is no longer required.

### CODE REVIEW

**Review by sumo-drosiek — CHANGES_REQUESTED** [review]
We should deprecate it before removing it. Not sure if the deprecation process is described, but this is more less how it looks like:

1. add deprecation information in readme, log deprecation warning in case argument is used and also add migration document
   https://github.com/SumoLogic/sumologic-otel-collector/pull/685/files
   Create issue with task for removal and add milestone with target tag version
1. remove feature except config and deprecation message (which need to be changed to removed attribute message), so customers have clear information what to do (in opposite to error which only indicates that the configuration doesn't exist anymore):
   https://github.com/SumoLogic/sumologic-otel-collector/pull/686/files

**Comment by echlebek** [comment]
@sumo-drosiek Understood, such a strategy for deprecation makes complete sense. However, I'm a little confused, since #875 didn't mention deprecation, and when I found the attribute, it appeared to have already been deprecated to some extent, as evidenced by the comment here: https://github.com/SumoLogic/sumologic-otel-collector/blob/main/pkg/exporter/sumologicexporter/config.go#L60

As for deprecation warnings, the deprecation warning you describe appears to have been removed since that PR landed, so I guess that these are also being cleaned up over time. Or, has the deprecation warning logic itself been moved?

I'm left wondering about what the actual stage of the maintenance lifecycle this attribute is in. Perhaps at this stage, only step #2 of your suggested workflow needs to be executed? Or perhaps the attribute was not actually deprecated as the comment describes.

I'm also wondering if this particular configuration option should really be carried forward, since it appears that it was only introduced as a workaround in the first place and doesn't seem to be mentioned in the README.

Thanks for any insight you can provide!

**Comment by sumo-drosiek** [comment]
> @sumo-drosiek Understood, such a strategy for deprecation makes complete sense. However, I'm a little confused, since #875 didn't mention deprecation, and when I found the attribute, it appeared to have already been deprecated to some extent, as evidenced by the comment here: https://github.com/SumoLogic/sumologic-otel-collector/blob/main/pkg/exporter/sumologicexporter/config.go#L60

Hmm, it should be added to the issue. Removing configuration option is a breaking change and we should be informative about it and provide migration document for such changes. It seems that this change has been deprecated, but only in the comment which you pointed out.
   
> As for deprecation warnings, the deprecation warning you describe appears to have been removed since that PR landed, so I guess that these are also being cleaned up over time. Or, has the deprecation warning logic itself been moved?

Yes, the deprecation warnings can be cleaned after some time. We didn't formalize it, but we keep them for few versions as it is more informative as default error from Otelcol.

> I'm left wondering about what the actual stage of the maintenance lifecycle this attribute is in. Perhaps at this stage, only step 2 of your suggested workflow needs to be executed? Or perhaps the attribute was not actually deprecated as the comment describes.
> I'm also wondering if this particular configuration option should really be carried forward, since it appears that it was only introduced as a workaround in the first place and doesn't seem to be mentioned in the README.

Maybe you're right, as this configuration has been added specifically for kubernetes collection. I would definitely go with deprecation document and maybe warning message, just in case

**Review by sumo-drosiek — APPROVED** [review]
@echlebek seems that this needs to be merged as we want to stop modyfing data in exporter. It was used only in helm chart so I think we can safely proceed with it. I can take over the PR to add remaining changes. WDYT?

**Comment by echlebek** [comment]
@sumo-drosiek I had forgotten about this! Please feel free to take it over. :bow:

**Review by swiatekm-sumo — APPROVED** [review]

**Pull request merged**
